name: "sonar_cloud_scan_github_actions"
on:
  workflow_dispatch:

jobs:
 lint:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
 
      - name: Lint
        run: ./gradlew lint  # Adjust for your linting tool
  DemoSonarCloudSCan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
            fetch-depth: 0
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
            GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
              -Dsonar.organization=paidahrithika
              -Dsonar.projectKey=PaidaHrithika_SonarCloudCodeAnalysis
              -Dsonar.analysis.enable=false
              -Dsonar.python.coverage.reportPaths=coverage.xml